### ISSUE TITLE
Mods failed to load: Not a valid mod

### ISSUE THREAD

**Issue by DragonflyShadows** [thesupersonic16/ManiaDynCam#1]
"ManiaDynCam: not a valid mod file." Looking around, it seems to happen to people using a version designed for an old version of Mania, but as far as I'm aware, there haven't been any updates since this version was created.

**Comment by thesupersonic16** [comment]
Sorry for not responding, I only just notice I did not have this repo on my Watching list. I have now updated the mod to the newest version of the game. You can get it [here](https://github.com/thesupersonic16/ManiaDynCam/releases). Thanks for reminding, I completely forgotten about this mod as I never published this on GB.

Anyways closing, open a new issue if there are any issues.
